\documentclass{article}

\usepackage{minted}
\usepackage{url}

\title{LINMA2710: Troubleshooting common issues for projects}
\author{Beno√Æt Legat}

\begin{document}

\maketitle

When writing C/C++ programs, we frequently encounters the problems raising the following questions:
\begin{enumerate}
\item Why is my program working on my computer but failing on my friend's computer or on Inginious?
\item When I debug my program, it is failing somewhere that was working before and what I just changed should not affect it?
\item My program was failing at a certain line, I have made an unrelated change and now it seems to work, how is that possible?
\end{enumerate}

These issues comes from the very permissive nature of C/C++ programs.

\section{Out of bounds in the stack}

Consider for instance the following:
\inputminted[linenos]{cpp}{troubleshoot1.cpp}
In line 8, we write 1000000 outside of the boundary of \texttt{a} but C/C++ does not prevent us from doing so.
What happens next is completely dependent on how the program was actually compiled and what the \texttt{sizeof(int)} bytes of memory located before the array \texttt{a} are used for.
For instance, if some compiler decides to place \texttt{i} before \texttt{a} in memory, this will set the value 1000000 to \texttt{i}.
On my computer, running it produces
\begin{minted}{sh}
$ g++ troubleshoot.cpp -o a.out
$ ./a.out
  1000000
[1]    342401 segmentation fault (core dumped)  ./a.out
\end{minted}
so \texttt{i} was indeed located before \texttt{a}.
While the error is located at line 8, the segfault only occurs at line 10!
Instead of raising an error, the mistake at line 8 silently modifies the value of \texttt{i}.
One way to debug a segfault is to compile the program with \texttt{-g}\footnote{See \url{https://sites.uclouvain.be/SystInfo/notes/Outils/html/gcc.html}.} and run a debugger like \texttt{gdb}\footnote{See \url{https://sites.uclouvain.be/SystInfo/notes/Outils/html/gdb.html}.}.
\begin{minted}{sh}
$ g++ -g troubleshoot.cpp -o a.out
$ gdb a.out
GNU gdb (GDB) 9.1
(...)
Reading symbols from a.out...
(gdb) run
Starting program: /home/blegat/git/LINMA2710/troubleshoot/a.out
1000000

Program received signal SIGBUS, Bus error.
0x00005555555551c9 in main () at troubleshoot.cpp:10
10	    a[i] = 0;
(gdb) p i
$1 = 1000000
(gdb) q
\end{minted}
Here, it might be confusing to see that the segfault occurs at line 10 since inspecting the code, we clearly see that this cannot fail.
The value of the variable \texttt{i} is obviously zero and \texttt{a[0] = 0;} should not fail.
Printing \texttt{p} in gdb shows 1000000 and gives a clue of what happened.

Another approach is to use valgrind\footnote{See \url{https://sites.uclouvain.be/SystInfo/notes/Outils/html/valgrind.html}. You may need to use the WSL (\url{https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux}) on windows for using valgrind.}:
\begin{minted}{sh}
$ valgrind ./a.out
==343429== Memcheck, a memory error detector
==343429== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==343429== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==343429== Command: ./a.out
==343429==
1000000
==343429== Invalid write of size 4
==343429==    at 0x1091C9: main (troubleshoot.cpp:10)
==343429==  Address 0x1fff3cff80 is not stack'd, malloc'd or (recently) free'd
==343429==
==343429==
==343429== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==343429==  Access not within mapped region at address 0x1FFF3CFF80
==343429==    at 0x1091C9: main (troubleshoot.cpp:10)
==343429==  If you believe this happened as a result of a stack
==343429==  overflow in your program's main thread (unlikely but
==343429==  possible), you can try to increase the size of the
==343429==  main thread stack using the --main-stacksize= flag.
==343429==  The main thread stack size used in this run was 8388608.
==343429==
==343429== HEAP SUMMARY:
==343429==     in use at exit: 0 bytes in 0 blocks
==343429==   total heap usage: 2 allocs, 2 frees, 73,728 bytes allocated
==343429==
==343429== All heap blocks were freed -- no leaks are possible
==343429==
==343429== For lists of detected and suppressed errors, rerun with: -s
==343429== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
[1]    343429 segmentation fault (core dumped)  valgrind ./a.out
\end{minted}
Here, valgrind does not detect the invalid write at line 8 so it would not have helped us.

One approach that would have worked is to ask the compiler to add checks for bounds with the \texttt{-fsanitize=address} option.
\begin{minted}[breaklines]{sh}
$ g++ -fsanitize=address -g troubleshoot.cpp
$ ./a.out
=================================================================
==343663==ERROR: AddressSanitizer: stack-buffer-underflow on address 0x7ffce9dc5acc at pc 0x556908b092c1 bp 0x7ffce9dc5a90 sp 0x7ffce9dc5a80
WRITE of size 4 at 0x7ffce9dc5acc thread T0
    #0 0x556908b092c0 in main /home/blegat/git/LINMA2710/troubleshoot/troubleshoot.cpp:8
    #1 0x7f4dd1d65022 in __libc_start_main (/usr/lib/libc.so.6+0x27022)
    #2 0x556908b0912d in _start (/home/blegat/git/LINMA2710/troubleshoot/a.out+0x112d)

Address 0x7ffce9dc5acc is located in stack of thread T0 at offset 28 in frame
    #0 0x556908b09208 in main /home/blegat/git/LINMA2710/troubleshoot/troubleshoot.cpp:5

  This frame has 1 object(s):
    [32, 40) 'a' (line 7) <== Memory access at offset 28 underflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-underflow /home/blegat/git/LINMA2710/troubleshoot/troubleshoot.cpp:8 in main
Shadow bytes around the buggy address:
  0x10001d3b0b00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10001d3b0b10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10001d3b0b20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10001d3b0b30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10001d3b0b40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x10001d3b0b50: 00 00 00 00 00 00 f1 f1 f1[f1]00 f3 f3 f3 00 00
  0x10001d3b0b60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10001d3b0b70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10001d3b0b80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10001d3b0b90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10001d3b0ba0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==343663==ABORTING
\end{minted}
We can interpret from ``\texttt{[32, 40) 'a' (line 7) <== Memory access at offset 28 underflows this variable}'' that \texttt{a[0]} is located at the bytes from 32 to 35, \texttt{a[1]} is located at the bytes from 36 to 39 and one tries to access it from the bytes 28 to 31 which is outside the array.

\section{Out of bounds in the heap}

Consider now a second example where \texttt{a} is created in the heap rather than the stack.
The location where the memory of \texttt{a} is allocated now depends not only on the compiler but also on the operation system (OS).
Indeed, the heap is managed by the OS and the OS needs to manage the partition of the heap into the allocated blocks (which is a difficult problem as each blocks need to be contiguous in memory but blocks are of different size and some are free'd which creates holes, etc..., this is similar to the OS task of partitioning the disk into files).
\inputminted[linenos]{cpp}{troubleshoot2.cpp}
As \texttt{i} is allocated in the stack and the stack is typically separated by some significant amount of memory from the head\footnote{See \url{https://sites.uclouvain.be/SystInfo/notes/Theorie/html/C/malloc.html#organisation-de-la-memoire}.}, \texttt{a[-1]} is not expected to point to the memory where \texttt{i} is stored.
When we run it:
\begin{minted}{sh}
$ g++ -g troubleshoot.cpp
$ ./a.out
0
\end{minted}
we see indeed that \texttt{i} was indeed not affected. However, this has corrupted the memory somewhere in the heap.
In this small program, this has no effect but in a larger program, this may corrupt the value of another variable.
This corruption depends not only on the OS but also on how the blocks of memory were allocated in the heap hence it depends on all allocation that occured, even if they are unrelated to \texttt{a}.
This makes the behavior of the program completely unpredictable.
It may fail quickly after the memory is corrupted, or this might lead to more corruption and only fail much later.
When running gdb until the failure occurs and printing the values of the variables there as we just did in the previous example, the state of the program might be so corrupted that it is impossible to make sense of their values.
To debug this situation, it is important to find the source of the corruption of the memory,
the first time it was corrupted.
Indeed, if a part of the program behaved unexpectedly because of a corruption that occured earlier, debugging this part won't help finding a bug in this part as there is none!
For this reason, it is important to sometimes step back from debugging a small portion of program and consider that the issue might have come earlier.

One way to do this is to look for the first issue detected by valgrind (note that some valgrind issues are false positive so it might not be the first).
\begin{minted}{sh}
$ valgrind ./a.out
==346281== Memcheck, a memory error detector
==346281== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==346281== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==346281== Command: ./a.out
==346281==
==346281== Invalid write of size 4
==346281==    at 0x10919E: main (troubleshoot.cpp:8)
==346281==  Address 0x4dc6c7c is 4 bytes before a block of size 8 alloc'd
==346281==    at 0x483A50F: operator new[](unsigned long) (vg_replace_malloc.c:433)
==346281==    by 0x109191: main (troubleshoot.cpp:7)
==346281==
0
==346281==
==346281== HEAP SUMMARY:
==346281==     in use at exit: 8 bytes in 1 blocks
==346281==   total heap usage: 3 allocs, 2 frees, 73,736 bytes allocated
==346281==
==346281== LEAK SUMMARY:
==346281==    definitely lost: 8 bytes in 1 blocks
==346281==    indirectly lost: 0 bytes in 0 blocks
==346281==      possibly lost: 0 bytes in 0 blocks
==346281==    still reachable: 0 bytes in 0 blocks
==346281==         suppressed: 0 bytes in 0 blocks
==346281== Rerun with --leak-check=full to see details of leaked memory
==346281==
==346281== For lists of detected and suppressed errors, rerun with: -s
==346281== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
\end{minted}
In this case, valgrind correctly finds the issue.
It also warns us that we did not free the memory allocated for \texttt{a}.

Compiling with \texttt{-fsanitize=address} also helps us identifying the issue.
\begin{minted}[breaklines]{sh}
$ g++ -fsanitize=address -g troubleshoot.cpp
$ ./a.out
=================================================================
==347127==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000000c at pc 0x560d1de1c245 bp 0x7ffcc8aeffa0 sp 0x7ffcc8aeff90
WRITE of size 4 at 0x60200000000c thread T0
    #0 0x560d1de1c244 in main /home/blegat/git/LINMA2710/troubleshoot/troubleshoot.cpp:8
    #1 0x7f3573349022 in __libc_start_main (/usr/lib/libc.so.6+0x27022)
    #2 0x560d1de1c11d in _start (/home/blegat/git/LINMA2710/troubleshoot/a.out+0x111d)

0x60200000000c is located 4 bytes to the left of 8-byte region [0x602000000010,0x602000000018)
allocated by thread T0 here:
    #0 0x7f3573943b78 in operator new[](unsigned long) /build/gcc/src/gcc/libsanitizer/asan/asan_new_delete.cc:107
    #1 0x560d1de1c201 in main /home/blegat/git/LINMA2710/troubleshoot/troubleshoot.cpp:7
    #2 0x7f3573349022 in __libc_start_main (/usr/lib/libc.so.6+0x27022)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/blegat/git/LINMA2710/troubleshoot/troubleshoot.cpp:8 in main
Shadow bytes around the buggy address:
  0x0c047fff7fb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7fc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7fd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c047fff8000: fa[fa]00 fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8010: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8020: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8030: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8040: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==347127==ABORTING
\end{minted}

\section{Conclusion}

In conclusion, try to use these tools to debug your issues, the output might be confusing at first but you will get used to it!
Even if your code does not fail, use these tools and check whether what they detect are false positives or issues with your code.
Indeed, even if your code seems to finish successfully on your computer, it does not mean that you have not corrupting the memory and that it would fail on another computer.
Another good practice to avoid such issues is to use defensive programming. Add many \texttt{assert}'s in your code to check what you know should be true, it might also help seeing failure early when the memory is corrupted and not much later in a part of the code completely unrelated.

\end{document}
